wip

diff --git a/.github/workflows/msys2.yaml b/.github/workflows/msys2.yaml
--- a/.github/workflows/msys2.yaml
+++ b/.github/workflows/msys2.yaml
@@ -125,6 +125,68 @@ jobs:
       - name: borgmatic rlist
         run: borgmatic rlist --config /tmp/borg/borgmatic.yaml
 
+
+
+  linuxborg:
+
+    # strategy:
+    #   fail-fast: true
+    #   matrix:
+    #     include:
+    #         - os: ubuntu-22.04
+    #           python-version: '3.9'
+    #           toxenv: mypy
+    #         - os: ubuntu-22.04
+    #           python-version: '3.11'
+    #           toxenv: docs
+    #         - os: ubuntu-22.04
+    #           python-version: '3.9'
+    #           toxenv: py39-fuse2
+    #         - os: ubuntu-22.04
+    #           python-version: '3.10'
+    #           toxenv: py310-fuse3
+    #         - os: ubuntu-22.04
+    #           python-version: '3.11'
+    #           toxenv: py311-fuse3
+    #         - os: ubuntu-22.04
+    #           python-version: '3.12'
+    #           toxenv: py312-fuse3
+
+    # env:
+    #   TOXENV: ${{ matrix.toxenv }}
+
+    runs-on: ubuntu-22.04
+    timeout-minutes: 60
+
+    steps:
+    - uses: actions/checkout@v3
+      with:
+        # just fetching 1 commit is not enough for setuptools-scm, so we fetch all
+        fetch-depth: 0
+    - name: Set up Python 3.11
+      uses: actions/setup-python@v4
+      with:
+        python-version: '3.11'
+
+    - name: Install Linux packages
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y pkg-config build-essential
+        sudo apt-get install -y libssl-dev libacl1-dev libxxhash-dev liblz4-dev libzstd-dev
+        sudo apt-get install -y libfuse-dev fuse || true  # Required for Python llfuse module
+        sudo apt-get install -y libfuse3-dev fuse3 || true  # Required for Python pyfuse3 module
+
+    - name: Install Python requirements
+      run: |
+        python -m pip install --upgrade pip setuptools wheel
+        #pip install -r requirements.d/development.txt
+    - name: Install borgbackup
+      run: |
+        pip install borgbackup==1.2.6
+        #python setup.py -v develop
+    - name: Show borg version
+      run: borg --version
+
   # msys2-clang64:
   #   runs-on: windows-latest
   #   defaults:
